/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Controller.Controlador;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author luisr
 */
public class Login extends javax.swing.JFrame {
    Controlador control = new Controlador();
    int cont = 0;
    String anterior;
    JTextField correo;
    JTextField codigo;
    JTextField password;
    JTextField password2;
   
    
    /**
     * Creates new form Login
     */
    public Login() {
        if (!control.verificarInicioServidor()) 
            control.iniciarServidor();
        initComponents();
        this.setLocationRelativeTo(null);
        control.restringirContraseña(txtContraseña);
        control.restringirUsuario(txtUsuario);
        txtUsuario.setBorder(BorderFactory.createCompoundBorder(null,BorderFactory.createEmptyBorder(0, 10, 0, 0 )));
        txtContraseña.setBorder(BorderFactory.createCompoundBorder(null,BorderFactory.createEmptyBorder(0, 10, 0, 0 )));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMinimizar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        btnIniciarSesion = new javax.swing.JButton();
        btnRC = new javax.swing.JButton();
        txtContraseña = new javax.swing.JPasswordField();
        fondoInicioSesion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnMinimizar.png"))); // NOI18N
        btnMinimizar.setBorder(null);
        btnMinimizar.setBorderPainted(false);
        btnMinimizar.setContentAreaFilled(false);
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnMinimizarPressed.png"))); // NOI18N
        btnMinimizar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnMinimizarPressed.png"))); // NOI18N
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 20, 20));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnCerrar.png"))); // NOI18N
        btnCerrar.setBorder(null);
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnCerrarPressed.png"))); // NOI18N
        btnCerrar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnCerrarPressed.png"))); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 20, 20));

        txtUsuario.setBackground(new java.awt.Color(43, 47, 58));
        txtUsuario.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(223, 223, 223));
        txtUsuario.setBorder(null);
        txtUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUsuario.setMargin(new java.awt.Insets(50, 1, 1, 1));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 240, 40));

        btnIniciarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnIniciarSesion.png"))); // NOI18N
        btnIniciarSesion.setBorder(null);
        btnIniciarSesion.setBorderPainted(false);
        btnIniciarSesion.setContentAreaFilled(false);
        btnIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciarSesion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnIniciarSesionPressed.png"))); // NOI18N
        btnIniciarSesion.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnIniciarSesionPressed.png"))); // NOI18N
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        btnIniciarSesion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnIniciarSesionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnIniciarSesionKeyReleased(evt);
            }
        });
        jPanel1.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 120, 40));

        btnRC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/olvidoContraseña.png"))); // NOI18N
        btnRC.setBorder(null);
        btnRC.setBorderPainted(false);
        btnRC.setContentAreaFilled(false);
        btnRC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRC.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/olvidoContraseñaPressed.png"))); // NOI18N
        btnRC.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/olvidoContraseñaPressed.png"))); // NOI18N
        btnRC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRCActionPerformed(evt);
            }
        });
        jPanel1.add(btnRC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 160, 20));

        txtContraseña.setBackground(new java.awt.Color(43, 47, 58));
        txtContraseña.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(223, 223, 223));
        txtContraseña.setBorder(null);
        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 240, 40));

        fondoInicioSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Login.png"))); // NOI18N
        jPanel1.add(fondoInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
    
        if (control.verificarUsuario(txtUsuario, txtContraseña)==1 || control.verificarUsuario(txtUsuario, txtContraseña)==2){
            Gestion gestion = new Gestion();
            control.mostrarVentana(gestion,this);
            if (control.verificarUsuario(txtUsuario, txtContraseña)==1){
                Gestion.txtPermisos.setForeground(new Color(167,18,16));
                Gestion.txtPermisos.setText("ADMINISTRADOR");
                
            }
            else {
                Gestion.txtPermisos.setForeground(new Color (0,168,236));
                Gestion.txtPermisos.setText("EMPLEADO");
                Gestion.btnUsuarios.setVisible(false);
                Gestion.jLabel1.setVisible(false);
            }
            
       } else if (control.verificarUsuario(txtUsuario, txtContraseña)==-1){ 
            JOptionPane.showMessageDialog(null, "Los datos ingresados son incorrectos","Credenciales incorrectas",JOptionPane.INFORMATION_MESSAGE);
            cont++;
            if (cont>1){
                if(!control.compararUsuarios(anterior, txtUsuario.getText()))
                    cont = 0;
                if (cont==3){
                    JOptionPane.showMessageDialog(null, "Su usuario ha sido bloqueado:\n -Si usted es administrador: Ingrese en '¿Olvidó su contraseña?'\n -Si usted es empleado: Comuniquese con su administrador ","Usuario bloqueado",JOptionPane.ERROR_MESSAGE);
                    control.bloquearEnBD(anterior);
                }
                    
            }
            anterior = txtUsuario.getText();
        } 
        if (control.verificarUsuario(txtUsuario, txtContraseña)==-2) 
            JOptionPane.showMessageDialog(null, "Su usuario esta bloqueado:\n -Si usted es administrador: Ingrese en '¿Olvidó su contraseña?'\n -Si usted es empleado: Comuniquese con su administrador ","Usuario bloqueado",JOptionPane.ERROR_MESSAGE);
      
             
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null,"¿Desea salir de la aplicacion?","Exit",dialog);
        if (result == 0){
            System.exit(0);
            control.desconectarBD();
        }
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnRCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRCActionPerformed
        RecuperarContraseña recuperar = new RecuperarContraseña();
        control.mostrarVentana(recuperar, this);
    }//GEN-LAST:event_btnRCActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void btnIniciarSesionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnIniciarSesionKeyReleased
       
    }//GEN-LAST:event_btnIniciarSesionKeyReleased

    private void btnIniciarSesionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnIniciarSesionKeyPressed
          
    }//GEN-LAST:event_btnIniciarSesionKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JButton btnRC;
    private javax.swing.JLabel fondoInicioSesion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
