/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Controller.Controlador;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author luisr
 */
public class RecuperarContraseña extends javax.swing.JFrame {
    String codigo;
    Controlador control = new Controlador();
    
    
    /**
     * Creates new form RecuperarContraseña
     */
    public RecuperarContraseña() {
        initComponents();
        control.iniciaVentana(this);
        btnSiguiente.setEnabled(false);
        control.restringirCodigo(txtCodigo);
        txtContraseña.setBorder(BorderFactory.createCompoundBorder(null,BorderFactory.createEmptyBorder(0, 10, 0, 0 )));
        txtContraseña2.setBorder(BorderFactory.createCompoundBorder(null,BorderFactory.createEmptyBorder(0, 10, 0, 0 )));
        txtCodigo.setBorder(BorderFactory.createCompoundBorder(null,BorderFactory.createEmptyBorder(0, 10, 0, 0 )));
        txtCorreo.setBorder(BorderFactory.createCompoundBorder(null,BorderFactory.createEmptyBorder(0, 10, 0, 0 )));
        progressBar.setVisible(false);
        control.restringirPassword(txtContraseña);
        control.restringirPassword(txtContraseña2);
        
        

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        pnlCorreo = new javax.swing.JPanel();
        lblInstruccion = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnEnviarCorreo = new javax.swing.JButton();
        txtCorreo = new javax.swing.JTextField();
        progressBar = new javax.swing.JProgressBar();
        lblFondo = new javax.swing.JLabel();
        pnlCodigo = new javax.swing.JPanel();
        lblInstruccion3 = new javax.swing.JLabel();
        btnCancelar1 = new javax.swing.JButton();
        btnSiguiente1 = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        lblFondo3 = new javax.swing.JLabel();
        pnlContraseña = new javax.swing.JPanel();
        lblInstruccion1 = new javax.swing.JLabel();
        btnCancelar2 = new javax.swing.JButton();
        btnSiguiente2 = new javax.swing.JButton();
        txtContraseña = new javax.swing.JTextField();
        txtContraseña2 = new javax.swing.JTextField();
        lblFondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(430, 320));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        pnlCorreo.setBackground(new java.awt.Color(36, 36, 36));
        pnlCorreo.setMinimumSize(new java.awt.Dimension(430, 320));
        pnlCorreo.setPreferredSize(new java.awt.Dimension(430, 320));
        pnlCorreo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInstruccion.setBackground(new java.awt.Color(204, 204, 0));
        lblInstruccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lblCorreoRC.png"))); // NOI18N
        pnlCorreo.add(lblInstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 300, 40));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnCancelarRC.png"))); // NOI18N
        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnCancelarRCPressed.png"))); // NOI18N
        btnCancelar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnCancelarRCPressed.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlCorreo.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 80, 30));

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnSiguiente.png"))); // NOI18N
        btnSiguiente.setBorder(null);
        btnSiguiente.setBorderPainted(false);
        btnSiguiente.setContentAreaFilled(false);
        btnSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSiguiente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnSiguientePressed.png"))); // NOI18N
        btnSiguiente.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnSiguientePressed.png"))); // NOI18N
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        pnlCorreo.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, 30));

        btnEnviarCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnEnviar.png"))); // NOI18N
        btnEnviarCorreo.setBorder(null);
        btnEnviarCorreo.setBorderPainted(false);
        btnEnviarCorreo.setContentAreaFilled(false);
        btnEnviarCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviarCorreo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnEnviarPressed.png"))); // NOI18N
        btnEnviarCorreo.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnEnviarPressed.png"))); // NOI18N
        btnEnviarCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarCorreoActionPerformed(evt);
            }
        });
        pnlCorreo.add(btnEnviarCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 70, 20));

        txtCorreo.setBackground(new java.awt.Color(43, 47, 58));
        txtCorreo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(223, 223, 223));
        txtCorreo.setBorder(null);
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        pnlCorreo.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 310, 30));

        progressBar.setBorder(null);
        progressBar.setBorderPainted(false);
        pnlCorreo.add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, 10));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/correo.png"))); // NOI18N
        pnlCorreo.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 320));

        jLayeredPane1.add(pnlCorreo, "card2");

        pnlCodigo.setBackground(new java.awt.Color(36, 36, 36));
        pnlCodigo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInstruccion3.setBackground(new java.awt.Color(204, 204, 0));
        lblInstruccion3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lblCodigoRC.png"))); // NOI18N
        pnlCodigo.add(lblInstruccion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 310, 30));

        btnCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnCancelarRC.png"))); // NOI18N
        btnCancelar1.setBorder(null);
        btnCancelar1.setBorderPainted(false);
        btnCancelar1.setContentAreaFilled(false);
        btnCancelar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnCancelarRCPressed.png"))); // NOI18N
        btnCancelar1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnCancelarRCPressed.png"))); // NOI18N
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });
        pnlCodigo.add(btnCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        btnSiguiente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnSiguiente.png"))); // NOI18N
        btnSiguiente1.setAutoscrolls(true);
        btnSiguiente1.setBorder(null);
        btnSiguiente1.setBorderPainted(false);
        btnSiguiente1.setContentAreaFilled(false);
        btnSiguiente1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSiguiente1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnSiguientePressed.png"))); // NOI18N
        btnSiguiente1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnSiguientePressed.png"))); // NOI18N
        btnSiguiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente1ActionPerformed(evt);
            }
        });
        pnlCodigo.add(btnSiguiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        txtCodigo.setBackground(new java.awt.Color(43, 47, 58));
        txtCodigo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(223, 223, 223));
        txtCodigo.setBorder(null);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        pnlCodigo.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 310, 30));

        lblFondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoCodigoRC.png"))); // NOI18N
        pnlCodigo.add(lblFondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 320));

        jLayeredPane1.add(pnlCodigo, "card2");

        pnlContraseña.setBackground(new java.awt.Color(36, 36, 36));
        pnlContraseña.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInstruccion1.setBackground(new java.awt.Color(204, 204, 0));
        lblInstruccion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lblPassRC.png"))); // NOI18N
        pnlContraseña.add(lblInstruccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 300, 30));

        btnCancelar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnCancelarRC.png"))); // NOI18N
        btnCancelar2.setBorder(null);
        btnCancelar2.setBorderPainted(false);
        btnCancelar2.setContentAreaFilled(false);
        btnCancelar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnCancelarRCPressed.png"))); // NOI18N
        btnCancelar2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnCancelarRCPressed.png"))); // NOI18N
        btnCancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar2ActionPerformed(evt);
            }
        });
        pnlContraseña.add(btnCancelar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        btnSiguiente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnSiguiente.png"))); // NOI18N
        btnSiguiente2.setBorder(null);
        btnSiguiente2.setBorderPainted(false);
        btnSiguiente2.setContentAreaFilled(false);
        btnSiguiente2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSiguiente2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnSiguientePressed.png"))); // NOI18N
        btnSiguiente2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnSiguientePressed.png"))); // NOI18N
        btnSiguiente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente2ActionPerformed(evt);
            }
        });
        pnlContraseña.add(btnSiguiente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        txtContraseña.setBackground(new java.awt.Color(43, 47, 58));
        txtContraseña.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(223, 223, 223));
        txtContraseña.setBorder(null);
        txtContraseña.setMargin(new java.awt.Insets(2, 2, 2, 2));
        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        pnlContraseña.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 300, 30));

        txtContraseña2.setBackground(new java.awt.Color(43, 47, 58));
        txtContraseña2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtContraseña2.setForeground(new java.awt.Color(223, 223, 223));
        txtContraseña2.setBorder(null);
        txtContraseña2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseña2ActionPerformed(evt);
            }
        });
        pnlContraseña.add(txtContraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 300, 30));

        lblFondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoPasswordRC.png"))); // NOI18N
        pnlContraseña.add(lblFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 320));

        jLayeredPane1.add(pnlContraseña, "card2");

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        pnlCorreo.setVisible(false);
        pnlCodigo.setVisible(true); 
        
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnEnviarCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarCorreoActionPerformed
        String correoPanaderia="panaderiahdo@gmail.com";
        String contrasenaPanaderia="panaderiahdo123$";
        
        if (control.verificarCorreoAdmin(txtCorreo)){
            codigo=control.generarCodigo();
            progressBar.setVisible(true);
            control.enviarCorreo(txtCorreo, correoPanaderia, contrasenaPanaderia, codigo);
            
            
            btnEnviarCorreo.setEnabled(false);
            
        }
        else JOptionPane.showMessageDialog(null, "El correo ingresado no se encuentra o no esta asociado a un administrador","Correo Invalido",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnEnviarCorreoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Login login = new Login();
        control.mostrarVentana(login, this);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        Login login = new Login();
        control.mostrarVentana(login, this);
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void btnSiguiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente1ActionPerformed
        if (txtCodigo.getText().equals(codigo)){
            pnlCodigo.setVisible(false);
            pnlContraseña.setVisible(true);
        } else JOptionPane.showMessageDialog(null, "El codigo ingresado es incorrecto. \nVerifique e intente de nuevo.","Codigo Invalido",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnSiguiente1ActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnCancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar2ActionPerformed
        Login login = new Login();
        control.mostrarVentana(login, this);
    }//GEN-LAST:event_btnCancelar2ActionPerformed

    private void btnSiguiente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente2ActionPerformed
        if (txtContraseña.getText().equals(txtContraseña2.getText())){
            if (control.verificarContraseña(txtContraseña)==true||control.verificarContraseña(txtContraseña2)==true){
                control.actualizarContraseña(txtCorreo, txtContraseña);
                JOptionPane.showMessageDialog(null, "Su contraseña ha sido cambiada con exito!","Exito",JOptionPane.INFORMATION_MESSAGE);
                Login login = new Login();
                control.mostrarVentana(login, this); 
            }
            else JOptionPane.showMessageDialog(null, "Debe introducir una contraseña mayor a 6 caracteres","Contraseña invalida",JOptionPane.ERROR_MESSAGE);
        } 
        else JOptionPane.showMessageDialog(null, "Las contraseñas introducidas no coinciden. \nVerifique e intente de nuevo.","Correo Invalido",JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_btnSiguiente2ActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void txtContraseña2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseña2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseña2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuperarContraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnCancelar2;
    public static javax.swing.JButton btnEnviarCorreo;
    public static javax.swing.JButton btnSiguiente;
    public static javax.swing.JButton btnSiguiente1;
    public static javax.swing.JButton btnSiguiente2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblFondo1;
    private javax.swing.JLabel lblFondo3;
    private javax.swing.JLabel lblInstruccion;
    private javax.swing.JLabel lblInstruccion1;
    private javax.swing.JLabel lblInstruccion3;
    private javax.swing.JPanel pnlCodigo;
    private javax.swing.JPanel pnlContraseña;
    private javax.swing.JPanel pnlCorreo;
    public static javax.swing.JProgressBar progressBar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtContraseña2;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
